
neff = getsweepdata('T_sweep','neff');
neff = neff;
T = getsweepdata('T_sweep','T');
plot(T,neff,'Temperature (K)','n_eff');
dn_eff = matrix(length(T),1);

fname="Temp_neff.txt";

if (fileexists(fname)) { rm(fname);} 

for(i=1:length(T)){ # loop over the length of the data
    dn_eff(i) = neff(i)-neff(1);
    write(fname,num2str(T(i))+" "+num2str(real(dn_eff(i)))+" "+num2str(imag(dn_eff(i))));
}

plot(T,dn_eff,"Temparature","dn_eff");
legend("real(dn_eff)","imag(dn_eff)");